item_available = [
    'Currency',
    'Stock Market',
    'GDP Growth Rate',
    'GDP Annual Growth Rate',
    'Unemployment Rate',
    'Inflation Rate',
    'Interest Rate',
    'Cash Reserve Ratio',
    'Balance of Trade',
    'Current Account',
    'Current Account to GDP',
    'Government Debt to GDP',
    'Government Budget',
    'Business Confidence',
    'Manufacturing PMI',
    'Services PMI',
    'Consumer Confidence',
    'Corporate Tax Rate',
    'Personal Income Tax Rate',
    'GDP',
    'GDP Constant Prices',
    'Gross National Product',
    'Gross Fixed Capital Formation',
    'GDP per Capita',
    'GDP per Capita PPP',
    'Full Year GDP Growth',
    'GDP from Agriculture',
    'GDP from Construction',
    'GDP from Manufacturing',
    'GDP from Mining',
    'GDP from Public Administration',
    'GDP from Utilities',
    'Labor Force Participation Rate',
    'Population',
    'Retirement Age Women',
    'Retirement Age Men',
    'Average Weekly Hours',
    'Employment Rate',
    'Minimum Wages',
    'Wages',
    'Consumer Price Index CPI',
    'GDP Deflator',
    'Producer Prices',
    'Producer Prices Change',
    'Export Prices',
    'Import Prices',
    'Food Inflation',
    'Producer Price Inflation MoM',
    'WPI Food Index YoY',
    'WPI Fuel YoY',
    'WPI Manufacturing YoY',
    'CPI Housing Utilities',
    'CPI Transportation',
    'Inflation Expectations',
    'Inflation Rate MoM',
    'Interbank Rate',
    'Money Supply M1',
    'Money Supply M2',
    'Money Supply M3',
    'Central Bank Balance Sheet',
    'Foreign Exchange Reserves',
    'Loan Growth',
    'Money Supply M0',
    'Reverse Repo Rate',
    'Exports',
    'Imports',
    'External Debt',
    'Terms of Trade',
    'Capital Flows',
    'Foreign Direct Investment',
    'Remittances',
    'Tourist Arrivals',
    'Gold Reserves',
    'Crude Oil Production',
    'Auto Exports',
    'Terrorism Index',
    'Weapons Sales',
    'Government Budget Value',
    'Government Spending',
    'Government Revenues',
    'Fiscal Expenditure',
    'Corruption Index',
    'Corruption Rank',
    'Credit Rating',
    'Government Spending to GDP',
    'Military Expenditure',
    'Sales Tax Rate',
    'Social Security Rate',
    'Social Security Rate For Companies',
    'Social Security Rate For Employees',
    'Withholding Tax Rate',
    'Industrial Production',
    'Industrial Production Mom',
    'Manufacturing Production',
    'Changes in Inventories',
    'Car Production',
    'Car Registrations',
    'Composite Leading Indicator',
    'Capacity Utilization',
    'Composite PMI',
    'Deposit Growth',
    'Electricity Production',
    'Mining Production',
    'Steel Production',
    'Total Vehicle Sales',
    'Consumer Spending',
    'Disposable Personal Income',
    'Bank Lending Rate',
    'Gasoline Prices',
    'Households Debt to GDP',
    'Housing Index',
    'Construction Output',
    'Residential Property Prices',
    'Hospital Beds'
]

items_not_scraped = [
    'Currency',
    'Stock Market',
    'Credit Rating'
]